Fix indentation of script

diff --git a/ppa/build-freetype b/ppa/build-freetype
--- a/ppa/build-freetype
+++ b/ppa/build-freetype
@@ -16,99 +16,100 @@ build_dir=$starting_dir/build-${package}-${dist}
 working_dir=$build_dir/${package}-${updated_version}
 
 remove_old_build() {
-	rm -rf ${build_dir}
-	mkdir ${build_dir}
+  rm -rf ${build_dir}
+  mkdir ${build_dir}
 }
 
 create_working_dir() {
-	cd ${build_dir}
-	apt-get source ${package}=${version}
+  cd ${build_dir}
+  apt-get source ${package}=${version}
 
-	# Remove old packages
-	rm *.orig.tar.gz
-	rm *.diff.gz
-	rm *.dsc
-	rm ${package}*/*.tar.bz2
+  # Remove old packages
+  rm *.orig.tar.gz
+  rm *.diff.gz
+  rm *.dsc
+  rm ${package}*/*.tar.bz2
 
-	mv ${package}* ${package}-${updated_version}/
+  mv ${package}* ${package}-${updated_version}/
 }
 
 fix_patches() {
-	cd $working_dir
+  cd $working_dir
 
   add_patch() {
     local patch_name=$1
     cp ${starting_dir}/infinality_bundle/01_freetype2-iu/$patch_name debian/patches-freetype/
-  	echo $patch_name >> debian/patches-freetype/series
+    echo $patch_name >> debian/patches-freetype/series
   }
 
   add_patch 0001-Enable-table-validation-modules.patch
   add_patch 0002-infinality-2.7-2016.09.09.patch
 
-	# Resolve conflict caused by infinality
-	sed -i -e '/freetype-2.1.7-backwards.compat.patch -p0/d' debian/patches-freetype/series
-	echo "freetype-2.1.7-backwards.compat.patch -F3 -p0" >> debian/patches-freetype/series
+  # Resolve conflict caused by infinality
+  sed -i -e '/freetype-2.1.7-backwards.compat.patch -p0/d' debian/patches-freetype/series
+  echo "freetype-2.1.7-backwards.compat.patch -F3 -p0" >> debian/patches-freetype/series
 
-	# Redundant
-	sed -i -e '/enable-subpixel-rendering.patch/d' debian/patches-freetype/series
+  # Redundant
+  sed -i -e '/enable-subpixel-rendering.patch/d' debian/patches-freetype/series
   sed -i -e '/enable-gxvalid-otvalid.patch/d' debian/patches-freetype/series
 
-	# remove since updated version changes things
-	sed -i -e '/0001-Revert-pcf-Signedness-fixes.patch/d' debian/patches-freetype/series
-	sed -i -e '/compiler_hardening_fixes.patch/d' debian/patches-ft2demos/series
+  # remove since updated version changes things
+  sed -i -e '/0001-Revert-pcf-Signedness-fixes.patch/d' debian/patches-freetype/series
+  sed -i -e '/compiler_hardening_fixes.patch/d' debian/patches-ft2demos/series
 }
 
 ignore_issues() {
-	cd $working_dir
-	# ignore compiler warnings
-	sed -i -e '/export DEB_CFLAGS_MAINT_APPEND := -Werror/d' debian/rules
-	# Level | Failure
-	# 0     | impossible (all checks disabled)
-	# 1     | symbols have disappeared
-	# 2     | symbols have been introduced
-	# 3     | libraries have disappeared
-	# 4     | libraries have been introduced
-	sed -i -e 's/DPKG_GENSYMBOLS_CHECK_LEVEL = 4/DPKG_GENSYMBOLS_CHECK_LEVEL = 0/' debian/rules
+  cd $working_dir
+  # ignore compiler warnings
+  sed -i -e '/export DEB_CFLAGS_MAINT_APPEND := -Werror/d' debian/rules
+  # Level | Failure
+  # 0     | impossible (all checks disabled)
+  # 1     | symbols have disappeared
+  # 2     | symbols have been introduced
+  # 3     | libraries have disappeared
+  # 4     | libraries have been introduced
+  sed -i -e 's/DPKG_GENSYMBOLS_CHECK_LEVEL = 4/DPKG_GENSYMBOLS_CHECK_LEVEL = 0/' debian/rules
 }
 
 update_changelog() {
-	cd $working_dir
-	CHANGELOG=$(mktemp)
-	cat <<-EOF > ${CHANGELOG}
-	${package} (${new_version}) ${dist}; urgency=low
+  cd $working_dir
+  CHANGELOG=$(mktemp)
 
-	  * Ignore compiler warnings
-	  * Update freetype to ${updated_version}
-	  * Remove unnecessary patches
-	  * Add infinality patch
-	  * Ignore extra symbols
+  cat <<EOF | sed 's/^  //' > ${CHANGELOG}
+  ${package} (${new_version}) ${dist}; urgency=low
 
-	 -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)
+    * Ignore compiler warnings
+    * Update freetype to ${updated_version}
+    * Remove unnecessary patches
+    * Add infinality patch
+    * Ignore extra symbols
+
+   -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)
 
 EOF
-	cat debian/changelog >> ${CHANGELOG}
-	mv ${CHANGELOG} debian/changelog
+  cat debian/changelog >> ${CHANGELOG}
+  mv ${CHANGELOG} debian/changelog
 }
 
 generate_package_from_ppa_archive() {
-	cd $build_dir
-	wget https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa/+files/freetype_${updated_version}.orig.tar.gz || return 1
-	tar xvzfp freetype_${updated_version}.orig.tar.gz
-	cd $working_dir
-	debuild -S -sd
+  cd $build_dir
+  wget https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa/+files/freetype_${updated_version}.orig.tar.gz || return 1
+  tar xvzfp freetype_${updated_version}.orig.tar.gz
+  cd $working_dir
+  debuild -S -sd
 }
 
 generate_package_from_official_archive() {
-	cd $working_dir
-	gpg --recv-keys E707FDA5
-	./debian/rules get-orig-source
-	mv *.orig.tar.gz ..
-	tar xvzfp ../*.orig.tar.gz --strip-components=1
-	debuild -S -sa
+  cd $working_dir
+  gpg --recv-keys E707FDA5
+  ./debian/rules get-orig-source
+  mv *.orig.tar.gz ..
+  tar xvzfp ../*.orig.tar.gz --strip-components=1
+  debuild -S -sa
 }
 
 upload_package_to_ppa() {
-	cd $build_dir
+  cd $build_dir
   dput -c ${starting_dir}/dput.cf ppa *changes
 }
 
